name: Deploy DRSOSystem

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Executar deploy na VPS
        shell: powershell
        run: |
          powershell -ExecutionPolicy Bypass -File C:\DRSOSystem\DRSOSystem\deploy\deploy.ps1